### ISSUE TITLE
withOpenFile

### ISSUE THREAD

**Issue by dbohdan** [dimkr/packlim#3]
Consider using the [withOpenFile](http://wiki.tcl.tk/39218) pattern for file access in `packlim.tcl`. In Jim it can be written as

``` Tcl
proc with-file {channel filename {access r} script} {
    upvar 1 $channel ch

    try {
        open $filename $access
    } on ok ch {
        uplevel 1 $script
    } finally {
        catch { close $ch }
    }
}
```

P.S.: Packlim is looking pretty good! If you ever have questions about Tcl (code or internals) feel free to drop by at #tcl on Freenode.

**Comment by dimkr** [comment]
Thanks for the suggestion! My second Tcl project, so I really appreciate the feedback.
